### ISSUE TITLE
Cannot delete mongod.exe on application stop: Will try to delete it again when program exits 

### ISSUE THREAD

**Issue by bence-takacs** [jirutka/embedmongo-spring#9]
When stopping the application it throws the following exception:

> could not delete C:\Users\me\AppData\Local\Temp\extract-ec5abf31-6172-41fe-b881-da09d0c367ebmongod.exe. Will try to delete it again when program exits.
> Exception in thread "Thread-2" java.lang.IllegalStateException: Shutdown in progress
>   at java.lang.ApplicationShutdownHooks.add(Unknown Source)
>   at java.lang.Runtime.addShutdownHook(Unknown Source)
>   at de.flapdoodle.embed.process.io.file.FileCleaner.forceDeleteOnExit(FileCleaner.java:52)
>   at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:125)
>   at de.flapdoodle.embed.process.extract.ExtractedFileSets.delete(ExtractedFileSets.java:76)
>   at de.flapdoodle.embed.process.store.ArtifactStore.removeFileSet(ArtifactStore.java:90)
>   at de.flapdoodle.embed.process.store.CachingArtifactStore$FilesWithCounter.forceDelete(CachingArtifactStore.java:176)
>   at de.flapdoodle.embed.process.store.CachingArtifactStore.removeAll(CachingArtifactStore.java:100)
>   at de.flapdoodle.embed.process.store.CachingArtifactStore$CacheCleaner.run(CachingArtifactStore.java:196)
>   at java.lang.Thread.run(Unknown Source)

It seems to be a well-known issue in flapdoodle code:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/issues/9
Hopefully only some configuration modification needed on this side
Weird thing: they mention CachingArtifactStore but current version of EmbeddedMongoBuilder using the deprecated ArtifactStoreBuilder.

Code used to init:

> @Configuration
> @EnableAutoConfiguration(exclude={EmbeddedMongoAutoConfiguration.class, MongoAutoConfiguration.class})
> @ComponentScan
> public class Application {
>     public static void main(String[] args) {
>       SpringApplication.run(Application.class, args);
>     }
>     @Bean(destroyMethod="close")
>     public Mongo mongo() throws IOException {
>         return new EmbeddedMongoBuilder()
>                 .version("2.6.11")
>                 .bindIp("127.0.0.1")
>                 .port(12345)
>                 .build();
>     }

**Comment by razorree** [comment]
The same happens with newest (2.1.1) de.flapdoodle.embed


2018-08-02 16:02:29.102  WARN 225356 --- [       Thread-3] d.f.embed.process.io.file.Files          : could not delete C:\Users\<user>\AppData\Local\Temp\extract-9fa9f09b-a479-4e23-a1e1-728e5b4aed4emongod.exe. Will try to delete it again when program exits.
Exception in thread "Thread-3" java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
	at de.flapdoodle.embed.process.io.file.FileCleaner.forceDeleteOnExit(FileCleaner.java:51)
	at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:128)
	at de.flapdoodle.embed.process.extract.ExtractedFileSets.delete(ExtractedFileSets.java:77)
	at de.flapdoodle.embed.process.store.ArtifactStore.removeFileSet(ArtifactStore.java:90)
	at de.flapdoodle.embed.process.store.CachingArtifactStore$FilesWithCounter.forceDelete(CachingArtifactStore.java:176)
	at de.flapdoodle.embed.process.store.CachingArtifactStore.removeAll(CachingArtifactStore.java:100)
	at de.flapdoodle.embed.process.store.CachingArtifactStore$CacheCleaner.run(CachingArtifactStore.java:196)
	at java.lang.Thread.run(Thread.java:748)


after running tests, this file is still in Temp directory (and after running it many times, i have many temp executables in temp directory)

**Comment by LeeBear35** [comment]
I have the same issue on Windows 10 environment, the MongoDB test directory has wiredtiger.lock file in it that cannot be deleted with the local user or admin account, so the file and folder are left behind.
